#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
polybar main &
polybar sidebar &
picom --config ~/.config/picom/picom.conf &

feh --bg-fill ~/Pictures/arch-black-4k.png &

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9
xrandr --output DP-0 --primary --auto --output HDMI-0 --auto --right-of DP-0
# bspc wm -O DP-0 HDMI-0

bspc config border_width 0
bspc config window_gap 12
# make all window transparency

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
